import { createTheme } from "@uiw/codemirror-themes";
import { tags as t } from "@lezer/highlight";

export const firaCodeDark = createTheme({
    theme: "dark",
    settings: {
      background: "#101B2D",
      foreground: "#FFFFFF",
      caret: "#61AFEE",
      gutterBorder: "#15222E",
      selectionMatch: "#036dd626",
      lineHighlight: "#036dd626",
      gutterBackground: "#15222E",
      gutterForeground: "#464E5F",
      fontFamily: '"Courier New", Courier, monospace',
    },
    styles: [
      { tag: t.comment, color: "#707681" },
      { tag: t.variableName, color: "#0080ff" },
      { tag: [t.string, t.special(t.brace)], color: "#9D5BD1" },
      { tag: t.number, color: "#9D5BD1" },
      { tag: t.bool, color: "#9D5BD1" },
      { tag: t.null, color: "#9D5BD1" },
      { tag: t.keyword, color: "#DC49A6" },
      { tag: t.operator, color: "#FFFFFF" },
      { tag: t.className, color: "#3BB178" },
      { tag: t.definition(t.typeName), color: "#5c6166" },
      { tag: t.typeName, color: "#5c6166" },
      { tag: t.angleBracket, color: "#3BB178" },
      { tag: t.tagName, color: "#3BB178" },
      { tag: t.attributeName, color: "#E34BA9" },
      { tag: t.brace, color: "#3BB178" },
      { tag: t.bracket, color: "#DB4E52" },
    ],
  });

export const ExpoTheme =  createTheme({
  theme: "dark",
  settings: {
    background: "#1B1D1E",
    foreground: "#BF7AF0",
    caret: "#61AFEE",
    gutterBorder: "#151718",
    selection: '#036dd626',
    selectionMatch: "#036dd626",
    lineHighlight: "transparent",
    gutterBackground: "#151718",
    gutterForeground: "#FFF",
  },
  styles: [
    { tag: t.comment, color: "#707681" },
    { tag: t.variableName, color: "#ECEDEE" },
    { tag: [t.string, t.special(t.brace)], color: "#EFC000" },
    { tag: t.number, color: "#9D5BD1" },
    { tag: t.bool, color: "#9D5BD1" },
    { tag: t.null, color: "#9D5BD1" },
    { tag: t.keyword, color: "#E34BA9" },
    { tag: t.operator, color: "#FFFFFF" },
    { tag: t.className, color: "#3BB178" },
    { tag: t.definition(t.typeName), color: "#5c6166" },
    { tag: t.typeName, color: "#5c6166" },
    { tag: t.angleBracket, color: "#687176" },
    { tag: t.tagName, color: "#3BB178" },
    { tag: t.attributeName, color: "#E34BA9" },
    { tag: t.brace, color: "#687176" },
    { tag: t.bracket, color: "#687176" },
  ],
})

export const GitHubDark =  createTheme({
  theme: 'dark',
  settings: {
    background: "#0E1117",
    foreground: "#C8D1D9",
    caret: "#61AFEE",
    gutterBorder: "#151718",
    selection: '#2F466C',
    selectionMatch: "#2F466C",
    lineHighlight: "transparent",
    gutterBackground: "#151718",
    gutterForeground: "#FFF",
  },
  styles: [
    { tag: t.comment, color: "#707681" },
    { tag: t.variableName, color: "#D1A8FE" },
    { tag: [t.string, t.special(t.brace)], color: "#8CB7D9" },
    { tag: t.number, color: "#79C0FF" },
    { tag: t.bool, color: "#79C0FF" },
    { tag: t.null, color: "#79C0FF" },
    { tag: t.keyword, color: "#FE7A72" },
    { tag: t.operator, color: "#6CABE5" },
    { tag: t.className, color: "#3BB178" },
    { tag: t.definition(t.typeName), color: "#5c6166" },
    { tag: t.typeName, color: "#5c6166" },
    { tag: t.angleBracket, color: "#687176" },
    { tag: t.tagName, color: "#3BB178" },
    { tag: t.attributeName, color: "#E34BA9" },
    { tag: t.brace, color: "#687176" },
    { tag: t.bracket, color: "#687176" },
  ]
})

export const PlayCode = createTheme({
  theme: 'dark',
  settings: {
    background: "#15222E",
    foreground: "#AAB2BF",
    caret: "#518BFF",
    gutterBorder: "#151718",
    selection: '#344255',
    selectionMatch: "#344255",
    lineHighlight: "transparent",
    gutterBackground: "#151718",
    gutterForeground: "#FFF",
  },
  styles: [
    { tag: t.comment, color: "#7F848E" },
    { tag: t.variableName, color: "#DF6B74" },
    { tag: [t.string, t.special(t.brace)], color: "#98C379" },
    { tag: t.number, color: "#D19A66" },
    { tag: t.bool, color: "#D19A66" },
    { tag: t.null, color: "#D19A66" },
    { tag: t.keyword, color: "#C678DC" },
    { tag: t.operator, color: "#55B6C2" },
    { tag: t.className, color: "#DF6B74" },
    { tag: t.definition(t.typeName), color: "#5c6166" },
    { tag: t.typeName, color: "#5c6166" },
    { tag: t.angleBracket, color: "#AAB2BF" },
    { tag: t.tagName, color: "#DF6B74" },
    { tag: t.attributeName, color: "#DF6B74" },
    { tag: t.brace, color: "#FFD601" },
    { tag: t.bracket, color: "#FFD601" },
  ]
})
